lib: [
  "_build/install/default/lib/Mini_fun/META"
  "_build/install/default/lib/Mini_fun/Mini_fun.a"
  "_build/install/default/lib/Mini_fun/Mini_fun.cma"
  "_build/install/default/lib/Mini_fun/Mini_fun.cmxa"
  "_build/install/default/lib/Mini_fun/Mini_fun.ml"
  "_build/install/default/lib/Mini_fun/Mini_fun.mli"
  "_build/install/default/lib/Mini_fun/dune-package"
  "_build/install/default/lib/Mini_fun/mini_fun.cmi"
  "_build/install/default/lib/Mini_fun/mini_fun.cmt"
  "_build/install/default/lib/Mini_fun/mini_fun.cmti"
  "_build/install/default/lib/Mini_fun/mini_fun.cmx"
  "_build/install/default/lib/Mini_fun/opam"
]
libexec: [
  "_build/install/default/lib/Mini_fun/Mini_fun.cmxs"
]
